package main

// LSP Completion Item Kind Constants
const (
	CompletionItemKindText          = 1
	CompletionItemKindMethod        = 2
	CompletionItemKindFunction      = 3
	CompletionItemKindConstructor   = 4
	CompletionItemKindField         = 5
	CompletionItemKindVariable      = 6
	CompletionItemKindClass         = 7
	CompletionItemKindInterface     = 8
	CompletionItemKindModule        = 9
	CompletionItemKindProperty      = 10
	CompletionItemKindUnit          = 11
	CompletionItemKindValue         = 12
	CompletionItemKindEnum          = 13
	CompletionItemKindKeyword       = 14
	CompletionItemKindSnippet       = 15
	CompletionItemKindColor         = 16
	CompletionItemKindFile          = 17
	CompletionItemKindReference     = 18
	CompletionItemKindFolder        = 19
	CompletionItemKindEnumMember    = 20
	CompletionItemKindConstant      = 21
	CompletionItemKindStruct        = 22
	CompletionItemKindEvent         = 23
	CompletionItemKindOperator      = 24
	CompletionItemKindTypeParameter = 25
)

// kindMap defines the mapping from ctags kinds to LSP completion item kinds
var kindMap = map[string]int{
	"alias":            CompletionItemKindVariable,
	"arg":              CompletionItemKindVariable,
	"attribute":        CompletionItemKindProperty,
	"boolean":          CompletionItemKindConstant,
	"callback":         CompletionItemKindFunction,
	"category":         CompletionItemKindEnum,
	"ccflag":           CompletionItemKindConstant,
	"cell":             CompletionItemKindVariable,
	"class":            CompletionItemKindClass,
	"collection":       CompletionItemKindClass,
	"command":          CompletionItemKindFunction,
	"component":        CompletionItemKindStruct,
	"config":           CompletionItemKindConstant,
	"const":            CompletionItemKindConstant,
	"constant":         CompletionItemKindConstant,
	"constructor":      CompletionItemKindConstructor,
	"context":          CompletionItemKindVariable,
	"counter":          CompletionItemKindVariable,
	"data":             CompletionItemKindVariable,
	"dataset":          CompletionItemKindVariable,
	"def":              CompletionItemKindFunction,
	"define":           CompletionItemKindConstant,
	"delegate":         CompletionItemKindClass,
	"enum":             CompletionItemKindEnum,
	"enumConstant":     CompletionItemKindEnumMember,
	"enumerator":       CompletionItemKindEnum,
	"environment":      CompletionItemKindVariable,
	"error":            CompletionItemKindEnum,
	"event":            CompletionItemKindEvent,
	"exception":        CompletionItemKindClass,
	"externvar":        CompletionItemKindVariable,
	"face":             CompletionItemKindInterface,
	"feature":          CompletionItemKindProperty,
	"field":            CompletionItemKindField,
	"fn":               CompletionItemKindFunction,
	"fun":              CompletionItemKindFunction,
	"func":             CompletionItemKindFunction,
	"function":         CompletionItemKindFunction,
	"functionVar":      CompletionItemKindVariable,
	"functor":          CompletionItemKindClass,
	"generic":          CompletionItemKindTypeParameter,
	"getter":           CompletionItemKindMethod,
	"global":           CompletionItemKindVariable,
	"globalVar":        CompletionItemKindVariable,
	"group":            CompletionItemKindEnum,
	"guard":            CompletionItemKindVariable,
	"handler":          CompletionItemKindFunction,
	"icon":             CompletionItemKindEnum,
	"id":               CompletionItemKindVariable,
	"implementation":   CompletionItemKindClass,
	"index":            CompletionItemKindVariable,
	"infoitem":         CompletionItemKindVariable,
	"inline":           CompletionItemKindKeyword,
	"inputSection":     CompletionItemKindKeyword,
	"instance":         CompletionItemKindVariable,
	"interface":        CompletionItemKindInterface,
	"it":               CompletionItemKindVariable,
	"jurisdiction":     CompletionItemKindVariable,
	"key":              CompletionItemKindKeyword,
	"keyInMiddle":      CompletionItemKindKeyword,
	"keyword":          CompletionItemKindKeyword,
	"kind":             CompletionItemKindKeyword,
	"l4subsection":     CompletionItemKindKeyword,
	"l5subsection":     CompletionItemKindKeyword,
	"label":            CompletionItemKindKeyword,
	"langdef":          CompletionItemKindKeyword,
	"legal":            CompletionItemKindKeyword,
	"legislation":      CompletionItemKindKeyword,
	"letter":           CompletionItemKindKeyword,
	"library":          CompletionItemKindModule,
	"list":             CompletionItemKindVariable,
	"local":            CompletionItemKindVariable,
	"localVariable":    CompletionItemKindVariable,
	"locale":           CompletionItemKindVariable,
	"localvar":         CompletionItemKindVariable,
	"macro":            CompletionItemKindVariable,
	"macroParameter":   CompletionItemKindVariable,
	"macrofile":        CompletionItemKindFile,
	"macroparam":       CompletionItemKindVariable,
	"makefile":         CompletionItemKindFile,
	"map":              CompletionItemKindVariable,
	"method":           CompletionItemKindMethod,
	"methodSpec":       CompletionItemKindMethod,
	"minorMode":        CompletionItemKindKeyword,
	"misc":             CompletionItemKindVariable,
	"module":           CompletionItemKindModule,
	"name":             CompletionItemKindVariable,
	"namespace":        CompletionItemKindModule,
	"nettype":          CompletionItemKindTypeParameter,
	"newFile":          CompletionItemKindFile,
	"node":             CompletionItemKindVariable,
	"object":           CompletionItemKindClass,
	"oneof":            CompletionItemKindEnum,
	"operator":         CompletionItemKindOperator,
	"option":           CompletionItemKindKeyword,
	"output":           CompletionItemKindVariable,
	"package":          CompletionItemKindModule,
	"param":            CompletionItemKindVariable,
	"parameter":        CompletionItemKindVariable,
	"paramEntity":      CompletionItemKindVariable,
	"part":             CompletionItemKindVariable,
	"pattern":          CompletionItemKindKeyword,
	"placeholder":      CompletionItemKindVariable,
	"port":             CompletionItemKindVariable,
	"process":          CompletionItemKindFunction,
	"property":         CompletionItemKindProperty,
	"prototype":        CompletionItemKindVariable,
	"protocol":         CompletionItemKindClass,
	"provider":         CompletionItemKindClass,
	"publication":      CompletionItemKindVariable,
	"qkey":             CompletionItemKindVariable,
	"receiver":         CompletionItemKindVariable,
	"record":           CompletionItemKindStruct,
	"reference":        CompletionItemKindReference,
	"region":           CompletionItemKindVariable,
	"register":         CompletionItemKindVariable,
	"repoid":           CompletionItemKindVariable,
	"report":           CompletionItemKindVariable,
	"repositoryId":     CompletionItemKindVariable,
	"repr":             CompletionItemKindVariable,
	"resource":         CompletionItemKindVariable,
	"response":         CompletionItemKindFunction,
	"role":             CompletionItemKindClass,
	"rpc":              CompletionItemKindVariable,
	"schema":           CompletionItemKindVariable,
	"script":           CompletionItemKindFile,
	"section":          CompletionItemKindKeyword,
	"selector":         CompletionItemKindKeyword,
	"sequence":         CompletionItemKindVariable,
	"server":           CompletionItemKindClass,
	"service":          CompletionItemKindClass,
	"setter":           CompletionItemKindMethod,
	"signal":           CompletionItemKindFunction,
	"singletonMethod":  CompletionItemKindMethod,
	"slot":             CompletionItemKindVariable,
	"software":         CompletionItemKindClass,
	"sourcefile":       CompletionItemKindFile,
	"standard":         CompletionItemKindVariable,
	"string":           CompletionItemKindText,
	"structure":        CompletionItemKindStruct,
	"stylesheet":       CompletionItemKindVariable,
	"subdir":           CompletionItemKindFolder,
	"submethod":        CompletionItemKindMethod,
	"submodule":        CompletionItemKindModule,
	"subprogram":       CompletionItemKindFunction,
	"subprogspec":      CompletionItemKindVariable,
	"subroutine":       CompletionItemKindFunction,
	"subsection":       CompletionItemKindVariable,
	"subst":            CompletionItemKindVariable,
	"substdef":         CompletionItemKindVariable,
	"tag":              CompletionItemKindVariable,
	"template":         CompletionItemKindVariable,
	"test":             CompletionItemKindVariable,
	"theme":            CompletionItemKindVariable,
	"theorem":          CompletionItemKindVariable,
	"thriftFile":       CompletionItemKindFile,
	"throwsparam":      CompletionItemKindVariable,
	"title":            CompletionItemKindVariable,
	"token":            CompletionItemKindVariable,
	"toplevelVariable": CompletionItemKindVariable,
	"trait":            CompletionItemKindVariable,
	"type":             CompletionItemKindStruct,
	"typealias":        CompletionItemKindVariable,
	"typedef":          CompletionItemKindTypeParameter,
	"typespec":         CompletionItemKindTypeParameter,
	"union":            CompletionItemKindStruct,
	"unit":             CompletionItemKindUnit,
	"username":         CompletionItemKindVariable,
	"val":              CompletionItemKindVariable,
	"value":            CompletionItemKindVariable,
	"var":              CompletionItemKindVariable,
	"variable":         CompletionItemKindVariable,
	"vector":           CompletionItemKindVariable,
	"version":          CompletionItemKindVariable,
	"video":            CompletionItemKindFile,
	"view":             CompletionItemKindVariable,
	"wrapper":          CompletionItemKindVariable,
	"xdata":            CompletionItemKindVariable,
	"xinput":           CompletionItemKindVariable,
	"xtask":            CompletionItemKindVariable,
}

// GetLSPCompletionKind retrieves the corresponding LSP completion item kind for a given ctags kind string
func GetLSPCompletionKind(ctagsKind string) int {
	if kind, ok := kindMap[ctagsKind]; ok {
		return kind
	}
	return CompletionItemKindText // Default to Text if no match is found
}
